# ============================================================
# EXERCISE 3 - VIDEO FORMAT CHECKER
#
# Launch:
#     python -m streamlit run app.py
#
# IMPORTANT:
# This app is designed to work with the UPDATED
# video_format_core.py containing:
#
#     process_video_for_coursework(...)
#     convert_video(...)
#     compliance_field_rows(...)
#     check_compliance(...)
#
# Main repair implemented here:
#
# 1. Uses process_video_for_coursework() for the official task.
# 2. Persists ORIGINAL verification rows.
# 3. Persists CONVERTED verification rows.
# 4. Separates Original / Converted verification in the UI.
# 5. Converted outputs must show 9 / 9 PASS.
# 6. Already-compliant files are not re-encoded by default.
# 7. Uses *_convertedOK.mp4 as the canonical coursework output.
# 8. Retains *_formatOK.mp4 alias generated by the core.
# ============================================================


from __future__ import annotations

import json
import shutil

from datetime import datetime
from pathlib import Path

import pandas as pd
import streamlit as st

from video_format_core import (
    DEFAULT_SPEC,
    SUPPORTED_VIDEO_EXTENSIONS,

    build_appendix_tables,
    build_fixed_vs_adaptive_comparison,

    check_compliance,
    choose_adaptive_bitrate,
    compliance_field_rows,
    convert_video,
    discover_toolchain,
    evaluate_transcoding_quality,
    extract_media_metrics,
    extract_thumbnail,
    generate_extension_report,
    generate_format_report,
    get_video_info,
    human_bytes,

    # --------------------------------------------------------
    # CRITICAL FIX
    # --------------------------------------------------------
    process_video_for_coursework,
)


# ============================================================
# DIRECTORIES
# ============================================================


BASE_DIR = (
    Path(
        __file__
    )
    .resolve()
    .parent
)


VIDEO_INPUT_DIR = (
    BASE_DIR
    / "videos"
    / "input"
)


OUTPUTS_DIR = (
    BASE_DIR
    / "outputs"
)


TEMP_DIR = (
    BASE_DIR
    / "temp"
)


ASSETS_DIR = (
    BASE_DIR
    / "assets"
)


for directory in [
    VIDEO_INPUT_DIR,
    OUTPUTS_DIR,
    TEMP_DIR,
]:

    directory.mkdir(
        parents=True,
        exist_ok=True,
    )


# ============================================================
# STREAMLIT PAGE CONFIGURATION
# ============================================================


st.set_page_config(
    page_title=(
        "Media Compliance Lab | "
        "Exercise 3"
    ),
    page_icon="🎞️",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# CSS
# ============================================================


css_path = (
    ASSETS_DIR
    / "styles.css"
)


if css_path.is_file():

    st.markdown(
        (
            "<style>"
            +
            css_path.read_text(
                encoding="utf-8"
            )
            +
            "</style>"
        ),
        unsafe_allow_html=True,
    )


# ============================================================
# TOOLCHAIN / SPECIFICATION
# ============================================================


TOOLS = (
    discover_toolchain()
)


SPEC = (
    DEFAULT_SPEC
)


# ============================================================
# FILE HELPERS
# ============================================================


def discover_input_videos(
) -> list[Path]:

    return sorted(
        [
            path

            for path
            in VIDEO_INPUT_DIR.iterdir()

            if (
                path.is_file()
                and
                path.suffix.lower()
                in SUPPORTED_VIDEO_EXTENSIONS
            )
        ]
    )


def save_uploaded_videos(
    uploaded_files,
) -> list[Path]:

    output_paths: list[
        Path
    ] = []

    for index, uploaded in enumerate(
        uploaded_files
        or [],
        start=1,
    ):

        safe_name = (
            Path(
                uploaded.name
            )
            .name
        )

        target = (
            TEMP_DIR
            /
            (
                f"upload_{index}_"
                + safe_name
            )
        )

        target.write_bytes(
            uploaded.getvalue()
        )

        output_paths.append(
            target
        )

    return output_paths


def copy_inputs(
    input_paths: list[Path],
    destination: Path,
) -> list[Path]:

    destination.mkdir(
        parents=True,
        exist_ok=True,
    )

    copied: list[
        Path
    ] = []

    used_names: set[
        str
    ] = set()

    for index, path in enumerate(
        input_paths,
        start=1,
    ):

        name = (
            path.name
        )

        if name in used_names:

            name = (
                f"{path.stem}"
                f"_{index}"
                f"{path.suffix}"
            )

        used_names.add(
            name
        )

        target = (
            destination
            / name
        )

        shutil.copy2(
            path,
            target,
        )

        copied.append(
            target
        )

    return copied


def save_json(
    path: Path,
    value,
) -> None:

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(
        path,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            value,
            file,
            indent=2,
            default=str,
        )


def read_csv_if_exists(
    path: Path,
) -> pd.DataFrame:

    if (
        not path.is_file()
        or
        path.stat().st_size == 0
    ):

        return pd.DataFrame()

    try:

        return pd.read_csv(
            path
        )

    except Exception:

        return pd.DataFrame()


def safe_download(
    label: str,
    path: Path,
    key: str,
    mime: str = "application/octet-stream",
    maximum_inline_mb: float = 150.0,
) -> None:

    if not path.is_file():

        return

    size_mb = (
        path.stat().st_size
        /
        (
            1024
            * 1024
        )
    )

    if (
        size_mb
        > maximum_inline_mb
    ):

        st.warning(
            (
                f"{path.name} is "
                f"{size_mb:.1f} MB. "
                "It remains available in the "
                "generated run directory."
            )
        )

        st.code(
            str(
                path.resolve()
            )
        )

        return

    with open(
        path,
        "rb",
    ) as file:

        st.download_button(
            label=label,
            data=file.read(),
            file_name=(
                path.name
            ),
            mime=mime,
            key=key,
            use_container_width=True,
        )


# ============================================================
# DATA HELPERS
# ============================================================


def normalise_details_dataframe(
    dataframe: pd.DataFrame,
) -> pd.DataFrame:
    """
    Ensure older saved result CSV files can still be displayed.

    New runs always contain the explicit 'stage' column:
        Original
        Converted
    """

    if dataframe.empty:

        return dataframe

    dataframe = (
        dataframe.copy()
    )

    if (
        "stage"
        not in dataframe.columns
    ):

        dataframe[
            "stage"
        ] = "Original"

    dataframe[
        "stage"
    ] = (
        dataframe[
            "stage"
        ]
        .fillna(
            "Original"
        )
    )

    return dataframe


def canonical_converted_files(
    directory: Path,
) -> list[Path]:
    """
    Show only *_convertedOK.mp4 in the principal conversion UI.

    video_format_core.py also creates *_formatOK.mp4, but that
    is an alias and should not appear as a duplicate conversion.
    """

    if not directory.is_dir():

        return []

    return sorted(
        directory.glob(
            "*_convertedOK.mp4"
        )
    )


def find_original_for_converted(
    converted_path: Path,
    inputs_directory: Path,
) -> Path | None:

    stem = (
        converted_path
        .stem
    )

    if stem.endswith(
        "_convertedOK"
    ):

        original_stem = (
            stem[
                :-len(
                    "_convertedOK"
                )
            ]
        )

    else:

        original_stem = (
            stem
        )

    if not inputs_directory.is_dir():

        return None

    matches = [
        path

        for path
        in inputs_directory.iterdir()

        if (
            path.is_file()
            and
            path.stem
            == original_stem
        )
    ]

    if matches:

        return matches[0]

    return None


# ============================================================
# DISPLAY HELPERS
# ============================================================


def show_metadata_metrics(
    metrics: dict,
) -> None:

    top = (
        st.columns(
            5
        )
    )

    top[0].metric(
        "Resolution",
        (
            f"{metrics.get('width', 0)}"
            " × "
            f"{metrics.get('height', 0)}"
        ),
    )

    fps = (
        metrics.get(
            "fps"
        )
    )

    top[1].metric(
        "FPS",
        (
            f"{fps:.3f}"
            if fps is not None
            else "—"
        ),
    )

    video_codec = (
        metrics.get(
            "video_codec"
        )
        or "—"
    )

    top[2].metric(
        "Video Codec",
        video_codec,
    )

    top[3].metric(
        "Video Bitrate",
        (
            f"{metrics.get('video_bitrate_kbps', 0):,}"
            " kb/s"
        ),
    )

    top[4].metric(
        "File Size",
        human_bytes(
            metrics.get(
                "file_size_bytes"
            )
        ),
    )

    bottom = (
        st.columns(
            5
        )
    )

    bottom[0].metric(
        "Container",
        (
            metrics.get(
                "container_display"
            )
            or
            metrics.get(
                "container"
            )
            or "—"
        ),
    )

    audio_codec = (
        metrics.get(
            "audio_codec"
        )
    )

    bottom[1].metric(
        "Audio Codec",
        (
            str(
                audio_codec
            ).upper()
            if audio_codec
            else "—"
        ),
    )

    bottom[2].metric(
        "Audio Bitrate",
        (
            f"{metrics.get('audio_bitrate_kbps', 0)}"
            " kb/s"
        ),
    )

    channels = (
        metrics.get(
            "audio_channels"
        )
    )

    bottom[3].metric(
        "Channels",
        (
            "2 / stereo"
            if channels == 2
            else (
                channels
                if channels is not None
                else "—"
            )
        ),
    )

    duration = (
        metrics.get(
            "duration_sec"
        )
    )

    bottom[4].metric(
        "Duration",
        (
            f"{duration:.2f}s"
            if duration is not None
            else "—"
        ),
    )


def show_specification(
) -> None:

    specification = pd.DataFrame(
        [
            {
                "Field":
                    "Container",

                "Required":
                    "MP4",
            },
            {
                "Field":
                    "Video codec",

                "Required":
                    "H.265 / HEVC",
            },
            {
                "Field":
                    "Resolution",

                "Required":
                    "854 × 480",
            },
            {
                "Field":
                    "Frame rate",

                "Required":
                    "25 fps",
            },
            {
                "Field":
                    "Aspect ratio",

                "Required":
                    "16:9",
            },
            {
                "Field":
                    "Video bitrate",

                "Required":
                    "2000–5000 kb/s",
            },
            {
                "Field":
                    "Audio codec",

                "Required":
                    "AAC",
            },
            {
                "Field":
                    "Audio bitrate",

                "Required":
                    "≤256 kb/s",
            },
            {
                "Field":
                    "Audio channels",

                "Required":
                    "2 / stereo",
            },
        ]
    )

    st.dataframe(
        specification,
        hide_index=True,
        use_container_width=True,
    )


def show_verification_table(
    rows: pd.DataFrame,
    stage: str,
) -> None:

    if rows.empty:

        st.info(
            (
                "No verification rows are "
                "available for this selection."
            )
        )

        return

    st.dataframe(
        rows[
            [
                "field",
                "expected",
                "actual",
                "status",
            ]
        ],
        hide_index=True,
        use_container_width=True,
    )

    failures = (
        rows[
            rows[
                "status"
            ]
            != "PASS"
        ]
    )

    if failures.empty:

        if (
            stage
            == "Converted"
        ):

            st.success(
                (
                    "✓ CONVERTED FILE VERIFIED — "
                    "all 9 mandatory Exercise 3 "
                    "fields PASS."
                )
            )

        else:

            st.success(
                (
                    "✓ ORIGINAL FILE IS ALREADY "
                    "COMPLIANT — all 9 fields PASS."
                )
            )

    else:

        if (
            stage
            == "Original"
        ):

            st.warning(
                (
                    f"Original submission contains "
                    f"{len(failures)} problematic "
                    "field(s). Automatic conversion "
                    "is required."
                )
            )

        else:

            st.error(
                (
                    f"Converted output contains "
                    f"{len(failures)} failing "
                    "field(s). This should not be "
                    "accepted as compliant."
                )
            )


# ============================================================
# HEADER
# ============================================================


header_left, header_right = (
    st.columns(
        [
            5,
            1.3,
        ]
    )
)


with header_left:

    st.markdown(
        """
        <div class="eyebrow">
            CM3065 · INTELLIGENT SIGNAL PROCESSING
        </div>

        <div class="main-title">
            Media Compliance Lab
        </div>

        <div class="main-subtitle">
            Exercise 3 · Video Format Inspection,
            H.265 Conversion and Quality Evaluation
        </div>
        """,
        unsafe_allow_html=True,
    )


with header_right:

    if (
        TOOLS.available
        and
        TOOLS.libx265_available
    ):

        status_text = (
            "SYSTEM READY"
        )

        status_class = (
            "system-status"
        )

    else:

        status_text = (
            "TOOLS MISSING"
        )

        status_class = (
            "system-status warning-status"
        )

    st.markdown(
        f"""
        <div class="{status_class}">
            <span class="status-dot"></span>
            {status_text}
        </div>
        """,
        unsafe_allow_html=True,
    )


# ============================================================
# PIPELINE STRIP
# ============================================================


st.markdown(
    """
    <div class="pipeline-strip">

        <span>VIDEO INPUT</span>
        <b>→</b>

        <span>FFPROBE</span>
        <b>→</b>

        <span>9-FIELD TEST</span>
        <b>→</b>

        <span>CONDITIONAL FIX</span>
        <b>→</b>

        <span>FFMPEG / H.265</span>
        <b>→</b>

        <span>FFPROBE AGAIN</span>
        <b>→</b>

        <span>9 / 9 PASS</span>

    </div>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# SIDEBAR
# ============================================================


with st.sidebar:

    st.markdown(
        "## Compliance Control"
    )

    st.caption(
        (
            "Exercise 3 · "
            "Video Format Checker"
        )
    )

    # --------------------------------------------------------
    # TOOLCHAIN
    # --------------------------------------------------------

    with st.expander(
        "FFmpeg Toolchain",
        expanded=False,
    ):

        st.write(
            "**ffprobe:**",
            (
                TOOLS.ffprobe
                or "Not found"
            ),
        )

        st.write(
            "**ffmpeg:**",
            (
                TOOLS.ffmpeg
                or "Not found"
            ),
        )

        st.write(
            "**libx265:**",
            (
                "Available"
                if TOOLS.libx265_available
                else "Not available"
            ),
        )

        if TOOLS.ffmpeg_version:

            st.caption(
                TOOLS.ffmpeg_version
            )

        if TOOLS.ffprobe_version:

            st.caption(
                TOOLS.ffprobe_version
            )

    # --------------------------------------------------------
    # VIDEO SOURCE
    # --------------------------------------------------------

    st.markdown(
        "### Video Source"
    )

    bundled_videos = (
        discover_input_videos()
    )

    source_mode = (
        st.radio(
            "Source",
            [
                "videos/input folder",
                "Upload video file(s)",
            ],
        )
    )

    selected_paths: list[
        Path
    ] = []

    if (
        source_mode
        == "videos/input folder"
    ):

        if bundled_videos:

            selected_names = (
                st.multiselect(
                    "Select videos",
                    [
                        path.name

                        for path
                        in bundled_videos
                    ],
                    default=[
                        path.name

                        for path
                        in bundled_videos
                    ],
                )
            )

            selected_paths = [
                path

                for path
                in bundled_videos

                if (
                    path.name
                    in selected_names
                )
            ]

        else:

            st.info(
                (
                    "Place the Exercise 3 videos "
                    "inside videos/input/."
                )
            )

    else:

        uploads = (
            st.file_uploader(
                "Upload video(s)",
                type=[
                    "mp4",
                    "mov",
                    "avi",
                    "mkv",
                    "m4v",
                ],
                accept_multiple_files=True,
            )
        )

        selected_paths = (
            save_uploaded_videos(
                uploads
            )
        )

    st.divider()

    # --------------------------------------------------------
    # OFFICIAL EXERCISE
    # --------------------------------------------------------

    st.markdown(
        "### Official Exercise 3"
    )

    operation = (
        st.radio(
            "Processing mode",
            [
                "Check + convert non-compliant",
                "Compliance check only",
            ],
        )
    )

    fixed_bitrate = (
        st.number_input(
            "Fixed H.265 bitrate (kb/s)",
            min_value=2000,
            max_value=5000,
            value=3000,
            step=100,
            disabled=True,
        )
    )

    st.caption(
        (
            "3000 kb/s is safely inside "
            "the required 2000–5000 kb/s range."
        )
    )

    force_fixed_conversion = (
        st.checkbox(
            (
                "Also convert already "
                "compliant videos"
            ),
            value=False,
            disabled=(
                operation
                == "Compliance check only"
            ),
        )
    )

    st.caption(
        (
            "For the normal coursework run, "
            "leave this unchecked."
        )
    )

    st.divider()

    # --------------------------------------------------------
    # EXTENSIONS
    # --------------------------------------------------------

    st.markdown(
        "### Extension Work"
    )

    enable_extensions = (
        st.checkbox(
            (
                "Enable Extensions "
                "3A + 3B"
            ),
            value=False,
            disabled=(
                operation
                == "Compliance check only"
            ),
        )
    )

    if (
        enable_extensions
        and
        operation
        != "Compliance check only"
    ):

        run_adaptive = (
            st.checkbox(
                (
                    "Adaptive H.265 "
                    "conversion"
                ),
                value=True,
            )
        )

        run_quality = (
            st.checkbox(
                (
                    "PSNR / SSIM "
                    "quality analysis"
                ),
                value=True,
            )
        )

        quality_samples = (
            st.slider(
                "Quality sample frames",
                min_value=4,
                max_value=30,
                value=12,
            )
        )

        temporal_samples = (
            st.slider(
                (
                    "Temporal complexity "
                    "samples"
                ),
                min_value=20,
                max_value=120,
                value=60,
                step=10,
            )
        )

    else:

        run_adaptive = False

        run_quality = False

        quality_samples = 12

        temporal_samples = 60

    st.divider()

    run_button = (
        st.button(
            "▶  RUN FORMAT ANALYSIS",
            type="primary",
            use_container_width=True,
        )
    )

    if st.button(
        "Clear previous results",
        use_container_width=True,
    ):

        st.session_state.pop(
            "exercise_3_last_run",
            None,
        )


# ============================================================
# MAIN TABS
# ============================================================


(
    compliance_tab,
    metadata_tab,
    conversion_tab,
    extension_tab,
    report_tab,
    configuration_tab,
) = st.tabs(
    [
        "✅ Compliance",
        "🔎 Metadata Inspector",
        "🎞 Transcoding",
        "📊 Quality & Adaptive",
        "📁 Reports & Downloads",
        "⚙ Configuration",
    ]
)


# ============================================================
# COMPLIANCE TAB
# ============================================================


with compliance_tab:

    st.markdown(
        "### Festival Delivery Specification"
    )

    show_specification()

    if selected_paths:

        st.markdown(
            "### Selected Inputs"
        )

        file_df = pd.DataFrame(
            [
                {
                    "File":
                        path.name,

                    "Type":
                        path.suffix.lower(),

                    "Size":
                        human_bytes(
                            path.stat().st_size
                        ),
                }

                for path
                in selected_paths
            ]
        )

        st.dataframe(
            file_df,
            hide_index=True,
            use_container_width=True,
        )

    compliance_status = (
        st.empty()
    )

    progress_placeholder = (
        st.empty()
    )

    current_task = (
        st.empty()
    )


# ============================================================
# METADATA TAB
# ============================================================


with metadata_tab:

    st.markdown(
        "### FFprobe Metadata Inspector"
    )

    st.caption(
        (
            "This inspector examines the selected "
            "submitted/original source file. "
            "Converted-file verification is available "
            "in the Compliance and Transcoding tabs."
        )
    )

    if not TOOLS.ffprobe:

        st.error(
            "ffprobe is not available."
        )

    elif selected_paths:

        metadata_file = (
            st.selectbox(
                "Inspect source video",
                selected_paths,
                format_func=lambda path:
                    Path(
                        path
                    ).name,
            )
        )

        try:

            info = (
                get_video_info(
                    metadata_file,
                    TOOLS,
                )
            )

            metrics = (
                extract_media_metrics(
                    metadata_file,
                    TOOLS,
                )
            )

            show_metadata_metrics(
                metrics
            )

            thumbnail = (
                extract_thumbnail(
                    metadata_file
                )
            )

            if thumbnail is not None:

                st.image(
                    thumbnail,
                    caption=(
                        metadata_file.name
                    ),
                    use_container_width=True,
                )

            st.markdown(
                "#### Original-file field compliance"
            )

            field_df = pd.DataFrame(
                compliance_field_rows(
                    metadata_file.name,
                    info,
                    SPEC,
                    stage="Original",
                )
            )

            show_verification_table(
                field_df,
                "Original",
            )

            with st.expander(
                "Raw ffprobe JSON"
            ):

                st.json(
                    info
                )

        except Exception as error:

            st.exception(
                error
            )

    else:

        st.info(
            "Select a source video to inspect."
        )


# ============================================================
# TAB CONTAINERS
# ============================================================


with conversion_tab:

    conversion_container = (
        st.container()
    )


with extension_tab:

    extension_container = (
        st.container()
    )


with report_tab:

    report_container = (
        st.container()
    )


# ============================================================
# CONFIGURATION TAB
# ============================================================


with configuration_tab:

    st.markdown(
        "### Current Application Configuration"
    )

    effective_buffer = max(
        int(
            SPEC.ffmpeg_buffer_kbps
        ),
        int(
            fixed_bitrate
        )
        * 2,
    )

    config_rows = [
        {
            "Parameter":
                "Container",

            "Value":
                "MP4",
        },
        {
            "Parameter":
                "Video codec",

            "Value":
                "H.265 / HEVC / libx265",
        },
        {
            "Parameter":
                "Video tag",

            "Value":
                "hvc1",
        },
        {
            "Parameter":
                "Resolution",

            "Value":
                "854 × 480",
        },
        {
            "Parameter":
                "Display aspect ratio",

            "Value":
                "16:9",
        },
        {
            "Parameter":
                "Frame rate",

            "Value":
                "25 fps CFR",
        },
        {
            "Parameter":
                "Fixed target bitrate",

            "Value":
                (
                    f"{int(fixed_bitrate)} "
                    "kb/s"
                ),
        },
        {
            "Parameter":
                "Permitted video bitrate",

            "Value":
                "2000–5000 kb/s",
        },
        {
            "Parameter":
                "VBV buffer",

            "Value":
                (
                    f"{effective_buffer} "
                    "kb"
                ),
        },
        {
            "Parameter":
                "Pixel format",

            "Value":
                "yuv420p",
        },
        {
            "Parameter":
                "Audio codec",

            "Value":
                "AAC",
        },
        {
            "Parameter":
                "Audio bitrate",

            "Value":
                (
                    f"{SPEC.fixed_audio_bitrate_kbps}"
                    " kb/s"
                ),
        },
        {
            "Parameter":
                "Audio channels",

            "Value":
                "2 / stereo",
        },
        {
            "Parameter":
                "Primary coursework suffix",

            "Value":
                "_convertedOK.mp4",
        },
        {
            "Parameter":
                "Rubric-compatible alias",

            "Value":
                "_formatOK.mp4",
        },
        {
            "Parameter":
                "MP4 optimization",

            "Value":
                "+faststart",
        },
    ]

    st.dataframe(
        pd.DataFrame(
            config_rows
        ),
        hide_index=True,
        use_container_width=True,
    )

    st.success(
        (
            "Official workflow: compliant originals "
            "are retained without unnecessary re-encoding; "
            "non-compliant originals are automatically "
            "converted and must pass all nine fields."
        )
    )

    st.markdown(
        "### Adaptive Bitrate Policy"
    )

    adaptive_policy = pd.DataFrame(
        [
            {
                "Complexity":
                    "Low",

                "Score":
                    "0–1",

                "Target":
                    "2400 kb/s",
            },
            {
                "Complexity":
                    "Medium",

                "Score":
                    "2–3",

                "Target":
                    "3000 kb/s",
            },
            {
                "Complexity":
                    "High",

                "Score":
                    "4–5",

                "Target":
                    "4000 kb/s",
            },
            {
                "Complexity":
                    "Very High",

                "Score":
                    "6+",

                "Target":
                    "4600 kb/s",
            },
        ]
    )

    st.dataframe(
        adaptive_policy,
        hide_index=True,
        use_container_width=True,
    )


# ============================================================
# EXECUTION
# ============================================================


if run_button:

    # --------------------------------------------------------
    # PRECONDITIONS
    # --------------------------------------------------------

    if not selected_paths:

        st.error(
            "Select at least one input video."
        )

        st.stop()

    if not TOOLS.ffprobe:

        st.error(
            (
                "ffprobe is required before "
                "Exercise 3 analysis can run."
            )
        )

        st.stop()

    conversion_enabled = (
        operation
        == "Check + convert non-compliant"
    )

    if (
        conversion_enabled
        and
        not TOOLS.ready_for_conversion
    ):

        st.error(
            (
                "FFmpeg with libx265 is required "
                "for automatic H.265 conversion."
            )
        )

        st.stop()

    if (
        run_adaptive
        and
        not TOOLS.ready_for_conversion
    ):

        st.error(
            (
                "Adaptive conversion requires "
                "FFmpeg with libx265."
            )
        )

        st.stop()

    # --------------------------------------------------------
    # RUN DIRECTORIES
    # --------------------------------------------------------

    timestamp = (
        datetime.now()
        .strftime(
            "%Y%m%d_%H%M%S"
        )
    )

    run_directory = (
        OUTPUTS_DIR
        /
        (
            f"run_{timestamp}"
        )
    )

    inputs_directory = (
        run_directory
        / "inputs"
    )

    fixed_directory = (
        run_directory
        / "fixed"
    )

    adaptive_directory = (
        run_directory
        / "adaptive"
    )

    results_directory = (
        run_directory
        / "results"
    )

    logs_directory = (
        run_directory
        / "logs"
    )

    for directory in [
        inputs_directory,
        fixed_directory,
        adaptive_directory,
        results_directory,
        logs_directory,
    ]:

        directory.mkdir(
            parents=True,
            exist_ok=True,
        )

    run_inputs = (
        copy_inputs(
            selected_paths,
            inputs_directory,
        )
    )

    # --------------------------------------------------------
    # SAVE CONFIGURATION
    # --------------------------------------------------------

    configuration = {
        "exercise":
            "Exercise 3",

        "created":
            timestamp,

        "festival_spec":
            SPEC.to_dict(),

        "operation":
            operation,

        "fixed_video_bitrate_kbps":
            int(
                fixed_bitrate
            ),

        "convert_already_compliant":
            force_fixed_conversion,

        "extensions_enabled":
            enable_extensions,

        "adaptive_conversion":
            run_adaptive,

        "quality_analysis":
            run_quality,

        "quality_sample_count":
            quality_samples,

        "temporal_sample_count":
            temporal_samples,

        "ffmpeg":
            TOOLS.ffmpeg,

        "ffprobe":
            TOOLS.ffprobe,

        "ffmpeg_version":
            TOOLS.ffmpeg_version,

        "ffprobe_version":
            TOOLS.ffprobe_version,

        "libx265_available":
            TOOLS.libx265_available,
    }

    save_json(
        results_directory
        / "run_config.json",
        configuration,
    )

    # --------------------------------------------------------
    # RESULT COLLECTION
    # --------------------------------------------------------

    compliance_rows: list[
        dict
    ] = []

    compliance_detail_rows: list[
        dict
    ] = []

    original_metadata_rows: list[
        dict
    ] = []

    fixed_quality_rows: list[
        dict
    ] = []

    adaptive_decision_rows: list[
        dict
    ] = []

    adaptive_quality_rows: list[
        dict
    ] = []

    progress_bar = (
        progress_placeholder
        .progress(
            0.0
        )
    )

    total_files = (
        len(
            run_inputs
        )
    )

    # --------------------------------------------------------
    # PROCESS EACH INPUT
    # --------------------------------------------------------

    for (
        file_index,
        input_path,
    ) in enumerate(
        run_inputs
    ):

        base_progress = (
            file_index
            / total_files
        )

        file_span = (
            1.0
            / total_files
        )

        def update_file_progress(
            local_fraction: float,
            message: str,
        ) -> None:

            progress_bar.progress(
                min(
                    1.0,
                    (
                        base_progress
                        +
                        (
                            file_span
                            * local_fraction
                        )
                    ),
                )
            )

            current_task.info(
                message
            )

        row = {
            "input_file":
                input_path.name,

            "original_status":
                None,

            "original_errors":
                "",

            "conversion_performed":
                False,

            "conversion_reason":
                "",

            "converted_file":
                "",

            "formatOK_file":
                "",

            "post_conversion_status":
                "",

            "post_conversion_errors":
                "",

            "all_nine_fields_pass":
                None,

            "fixed_processing_seconds":
                None,

            "extension_errors":
                "",
        }

        fixed_output: Path | None = (
            None
        )

        adaptive_output: Path | None = (
            None
        )

        adaptive_decision = (
            None
        )

        # ====================================================
        # OFFICIAL EXERCISE 3
        # ====================================================

        try:

            update_file_progress(
                0.02,
                (
                    "Inspecting "
                    f"{input_path.name}"
                ),
            )

            if conversion_enabled:

                # ------------------------------------------------
                # CRITICAL FIX:
                #
                # Use the core's official conditional workflow.
                # ------------------------------------------------

                def official_progress(
                    fraction,
                    message,
                ) -> None:

                    update_file_progress(
                        (
                            0.05
                            +
                            0.42
                            * fraction
                        ),
                        message,
                    )

                coursework_result = (
                    process_video_for_coursework(
                        input_path=(
                            input_path
                        ),
                        output_directory=(
                            fixed_directory
                        ),
                        tools=(
                            TOOLS
                        ),
                        selected_video_bitrate_kbps=(
                            int(
                                fixed_bitrate
                            )
                        ),
                        spec=(
                            SPEC
                        ),
                        convert_already_compliant=(
                            force_fixed_conversion
                        ),
                        progress_callback=(
                            official_progress
                        ),
                    )
                )

                # --------------------------------------------
                # ORIGINAL INFORMATION
                # --------------------------------------------

                original_info = (
                    coursework_result[
                        "original_info"
                    ]
                )

                original_errors = list(
                    coursework_result.get(
                        "original_errors",
                        [],
                    )
                )

                original_rows = list(
                    coursework_result.get(
                        "original_field_rows",
                        [],
                    )
                )

                original_metrics = (
                    coursework_result.get(
                        "original_metrics"
                    )
                    or
                    coursework_result.get(
                        "source_metrics"
                    )
                )

                if original_metrics is None:

                    original_metrics = (
                        extract_media_metrics(
                            input_path,
                            TOOLS,
                        )
                    )

                original_metadata_rows.append(
                    original_metrics
                )

                # --------------------------------------------
                # CRITICAL FIX:
                # persist ORIGINAL rows
                # --------------------------------------------

                compliance_detail_rows.extend(
                    original_rows
                )

                row[
                    "original_status"
                ] = (
                    "COMPLIANT"
                    if coursework_result.get(
                        "original_compliant",
                        False,
                    )
                    else "NON-COMPLIANT"
                )

                row[
                    "original_errors"
                ] = "; ".join(
                    original_errors
                )

                row[
                    "conversion_performed"
                ] = bool(
                    coursework_result.get(
                        "conversion_performed",
                        False,
                    )
                )

                row[
                    "conversion_reason"
                ] = str(
                    coursework_result.get(
                        "conversion_reason",
                        "",
                    )
                )

                # --------------------------------------------
                # CONVERTED INFORMATION
                # --------------------------------------------

                if row[
                    "conversion_performed"
                ]:

                    converted_rows = list(
                        coursework_result.get(
                            "converted_field_rows",
                            [],
                        )
                    )

                    # ----------------------------------------
                    # CRITICAL FIX:
                    # persist CONVERTED rows
                    # ----------------------------------------

                    compliance_detail_rows.extend(
                        converted_rows
                    )

                    converted_path_text = (
                        coursework_result.get(
                            "convertedOK_path"
                        )
                        or
                        coursework_result.get(
                            "converted_path"
                        )
                        or
                        coursework_result.get(
                            "output_path"
                        )
                    )

                    if converted_path_text:

                        fixed_output = Path(
                            converted_path_text
                        )

                    converted_file_text = (
                        coursework_result.get(
                            "converted_file"
                        )
                    )

                    if converted_file_text:

                        row[
                            "converted_file"
                        ] = str(
                            converted_file_text
                        )

                    elif fixed_output is not None:

                        row[
                            "converted_file"
                        ] = (
                            fixed_output.name
                        )

                    format_ok_text = (
                        coursework_result.get(
                            "formatOK_path"
                        )
                    )

                    if format_ok_text:

                        row[
                            "formatOK_file"
                        ] = (
                            Path(
                                format_ok_text
                            )
                            .name
                        )

                    converted_compliant = bool(
                        coursework_result.get(
                            "converted_compliant",
                            False,
                        )
                    )

                    nine_pass = bool(
                        coursework_result.get(
                            "all_nine_fields_pass",
                            False,
                        )
                    )

                    row[
                        "all_nine_fields_pass"
                    ] = (
                        nine_pass
                    )

                    converted_errors = list(
                        coursework_result.get(
                            "converted_errors",
                            [],
                        )
                    )

                    if (
                        converted_compliant
                        and
                        nine_pass
                    ):

                        row[
                            "post_conversion_status"
                        ] = "COMPLIANT"

                    else:

                        row[
                            "post_conversion_status"
                        ] = (
                            "STILL NON-COMPLIANT"
                        )

                        row[
                            "post_conversion_errors"
                        ] = "; ".join(
                            converted_errors
                        )

                else:

                    # Already-compliant original.
                    row[
                        "post_conversion_status"
                    ] = "NOT REQUIRED"

                    row[
                        "all_nine_fields_pass"
                    ] = None

            else:

                # ============================================
                # COMPLIANCE CHECK ONLY
                # ============================================

                original_info = (
                    get_video_info(
                        input_path,
                        TOOLS,
                    )
                )

                original_metrics = (
                    extract_media_metrics(
                        input_path,
                        TOOLS,
                    )
                )

                original_metadata_rows.append(
                    original_metrics
                )

                original_rows = (
                    compliance_field_rows(
                        input_path.name,
                        original_info,
                        SPEC,
                        stage="Original",
                    )
                )

                compliance_detail_rows.extend(
                    original_rows
                )

                original_errors = (
                    check_compliance(
                        original_info,
                        SPEC,
                    )
                )

                row[
                    "original_status"
                ] = (
                    "NON-COMPLIANT"
                    if original_errors
                    else "COMPLIANT"
                )

                row[
                    "original_errors"
                ] = "; ".join(
                    original_errors
                )

                if original_errors:

                    row[
                        "post_conversion_status"
                    ] = (
                        "CONVERSION SKIPPED"
                    )

                else:

                    row[
                        "post_conversion_status"
                    ] = (
                        "NOT REQUIRED"
                    )

                row[
                    "conversion_reason"
                ] = (
                    "Compliance-check-only mode."
                )

            update_file_progress(
                0.50,
                (
                    "Official Exercise 3 analysis "
                    f"complete: {input_path.name}"
                ),
            )

        except Exception as error:

            if (
                row[
                    "original_status"
                ]
                is None
            ):

                row[
                    "original_status"
                ] = "ERROR"

                row[
                    "original_errors"
                ] = str(
                    error
                )

            else:

                row[
                    "post_conversion_status"
                ] = (
                    "PROCESSING ERROR"
                )

                row[
                    "post_conversion_errors"
                ] = str(
                    error
                )

        # ====================================================
        # OPTIONAL EXTENSIONS
        #
        # Extension errors are deliberately isolated from the
        # official coursework result. A PSNR/adaptive failure
        # must not overwrite a successful official conversion.
        # ====================================================

        extension_error_messages: list[
            str
        ] = []

        # ----------------------------------------------------
        # ADAPTIVE H.265
        # ----------------------------------------------------

        if run_adaptive:

            try:

                update_file_progress(
                    0.52,
                    (
                        "Estimating adaptive complexity: "
                        f"{input_path.name}"
                    ),
                )

                adaptive_decision = (
                    choose_adaptive_bitrate(
                        input_path,
                        TOOLS,
                        SPEC,
                        temporal_samples=(
                            temporal_samples
                        ),
                    )
                )

                adaptive_output = (
                    adaptive_directory
                    /
                    (
                        f"{input_path.stem}"
                        "_adaptiveH265_"
                        "convertedOK.mp4"
                    )
                )

                selected_bitrate = int(
                    adaptive_decision[
                        "selected_bitrate_kbps"
                    ]
                )

                def adaptive_progress(
                    fraction,
                    message,
                ) -> None:

                    update_file_progress(
                        (
                            0.55
                            +
                            0.25
                            * fraction
                        ),
                        (
                            "Adaptive "
                            f"{selected_bitrate} kb/s: "
                            + message
                        ),
                    )

                adaptive_conversion = (
                    convert_video(
                        input_path=(
                            input_path
                        ),
                        output_path=(
                            adaptive_output
                        ),
                        tools=(
                            TOOLS
                        ),
                        selected_video_bitrate_kbps=(
                            selected_bitrate
                        ),
                        spec=(
                            SPEC
                        ),
                        progress_callback=(
                            adaptive_progress
                        ),
                    )
                )

                adaptive_decision.update(
                    {
                        "adaptive_output_file":
                            adaptive_output.name,

                        "adaptive_conversion_status":
                            (
                                "COMPLIANT"
                                if adaptive_conversion.get(
                                    "converted_compliant",
                                    adaptive_conversion.get(
                                        "compliant",
                                        False,
                                    ),
                                )
                                else "NON-COMPLIANT"
                            ),

                        "adaptive_conversion_errors":
                            "; ".join(
                                adaptive_conversion.get(
                                    "converted_errors",
                                    adaptive_conversion.get(
                                        "compliance_errors",
                                        [],
                                    ),
                                )
                            ),

                        "adaptive_processing_seconds":
                            round(
                                adaptive_conversion[
                                    "processing_time_seconds"
                                ],
                                3,
                            ),
                    }
                )

                adaptive_decision_rows.append(
                    adaptive_decision
                )

            except Exception as error:

                extension_error_messages.append(
                    (
                        "Adaptive conversion: "
                        + str(
                            error
                        )
                    )
                )

                adaptive_output = None

        # ----------------------------------------------------
        # QUALITY ANALYSIS
        # ----------------------------------------------------

        if run_quality:

            try:

                update_file_progress(
                    0.82,
                    (
                        "Evaluating visual quality: "
                        f"{input_path.name}"
                    ),
                )

                if (
                    fixed_output is not None
                    and
                    fixed_output.is_file()
                ):

                    fixed_quality_rows.append(
                        evaluate_transcoding_quality(
                            original_path=(
                                input_path
                            ),
                            converted_path=(
                                fixed_output
                            ),
                            tools=(
                                TOOLS
                            ),
                            conversion_type=(
                                "Fixed 3000 kb/s"
                            ),
                            selected_bitrate_kbps=(
                                int(
                                    fixed_bitrate
                                )
                            ),
                            sample_count=(
                                quality_samples
                            ),
                            spec=(
                                SPEC
                            ),
                        )
                    )

                if (
                    adaptive_output is not None
                    and
                    adaptive_output.is_file()
                    and
                    adaptive_decision is not None
                ):

                    adaptive_quality_rows.append(
                        evaluate_transcoding_quality(
                            original_path=(
                                input_path
                            ),
                            converted_path=(
                                adaptive_output
                            ),
                            tools=(
                                TOOLS
                            ),
                            conversion_type=(
                                "Adaptive bitrate"
                            ),
                            selected_bitrate_kbps=(
                                int(
                                    adaptive_decision[
                                        "selected_bitrate_kbps"
                                    ]
                                )
                            ),
                            sample_count=(
                                quality_samples
                            ),
                            spec=(
                                SPEC
                            ),
                        )
                    )

            except Exception as error:

                extension_error_messages.append(
                    (
                        "Quality analysis: "
                        + str(
                            error
                        )
                    )
                )

        if extension_error_messages:

            row[
                "extension_errors"
            ] = " | ".join(
                extension_error_messages
            )

        compliance_rows.append(
            row
        )

        update_file_progress(
            1.0,
            (
                "Finished "
                f"{input_path.name}"
            ),
        )

    # ========================================================
    # BUILD DATAFRAMES
    # ========================================================

    compliance_df = (
        pd.DataFrame(
            compliance_rows
        )
    )

    compliance_details_df = (
        pd.DataFrame(
            compliance_detail_rows
        )
    )

    metadata_df = (
        pd.DataFrame(
            original_metadata_rows
        )
    )

    fixed_quality_df = (
        pd.DataFrame(
            fixed_quality_rows
        )
    )

    adaptive_decisions_df = (
        pd.DataFrame(
            adaptive_decision_rows
        )
    )

    adaptive_quality_df = (
        pd.DataFrame(
            adaptive_quality_rows
        )
    )

    # ========================================================
    # SAVE OFFICIAL RESULTS
    # ========================================================

    compliance_df.to_csv(
        results_directory
        / "final_compliance_results.csv",
        index=False,
    )

    compliance_details_df.to_csv(
        results_directory
        / "compliance_field_details.csv",
        index=False,
    )

    metadata_df.to_csv(
        results_directory
        / "original_metadata.csv",
        index=False,
    )

    format_report = (
        generate_format_report(
            compliance_df
        )
    )

    format_report_path = (
        logs_directory
        / "format_report.txt"
    )

    format_report_path.write_text(
        format_report,
        encoding="utf-8",
    )

    # ========================================================
    # SAVE EXTENSION RESULTS
    # ========================================================

    if not fixed_quality_df.empty:

        fixed_quality_df.to_csv(
            results_directory
            / "fixed_quality.csv",
            index=False,
        )

    if not adaptive_decisions_df.empty:

        adaptive_decisions_df.to_csv(
            results_directory
            / "adaptive_bitrate_decisions.csv",
            index=False,
        )

    if not adaptive_quality_df.empty:

        adaptive_quality_df.to_csv(
            results_directory
            / "adaptive_quality.csv",
            index=False,
        )

    comparison_df = (
        build_fixed_vs_adaptive_comparison(
            fixed_quality_df,
            adaptive_quality_df,
            adaptive_decisions_df,
        )
    )

    if not comparison_df.empty:

        comparison_df.to_csv(
            results_directory
            / "fixed_vs_adaptive_comparison.csv",
            index=False,
        )

        (
            appendix_summary,
            bitrate_decision_table,
            quality_comparison_table,
        ) = build_appendix_tables(
            comparison_df
        )

        if not appendix_summary.empty:

            appendix_summary.to_csv(
                results_directory
                / "appendix_summary_table.csv",
                index=False,
            )

        if not bitrate_decision_table.empty:

            bitrate_decision_table.to_csv(
                results_directory
                / "bitrate_decision_table.csv",
                index=False,
            )

        if not quality_comparison_table.empty:

            quality_comparison_table.to_csv(
                results_directory
                / "quality_comparison_table.csv",
                index=False,
            )

        extension_report = (
            generate_extension_report(
                comparison_df
            )
        )

        (
            logs_directory
            / "exercise3_extension_report.txt"
        ).write_text(
            extension_report,
            encoding="utf-8",
        )

    # ========================================================
    # CREATE COMPLETE RUN ARCHIVE
    # ========================================================

    archive_base = (
        OUTPUTS_DIR
        /
        (
            f"{run_directory.name}"
            "_bundle"
        )
    )

    archive_path = Path(
        shutil.make_archive(
            str(
                archive_base
            ),
            "zip",
            root_dir=(
                run_directory
            ),
        )
    )

    # ========================================================
    # SESSION STATE
    # ========================================================

    st.session_state[
        "exercise_3_last_run"
    ] = {
        "run_directory":
            str(
                run_directory
            ),

        "archive_path":
            str(
                archive_path
            ),
    }

    progress_bar.progress(
        1.0
    )

    official_errors = int(
        (
            compliance_df[
                "original_status"
            ]
            == "ERROR"
        ).sum()
        +
        (
            compliance_df[
                "post_conversion_status"
            ]
            == "PROCESSING ERROR"
        ).sum()
    )

    if official_errors == 0:

        compliance_status.success(
            (
                "✓ Exercise 3 processing complete. "
                "Official compliance workflow finished "
                "without processing errors."
            )
        )

    else:

        compliance_status.error(
            (
                f"Exercise 3 completed with "
                f"{official_errors} official "
                "processing error(s)."
            )
        )

    current_task.success(
        (
            "All selected videos "
            "have been processed."
        )
    )

    st.toast(
        "Exercise 3 completed.",
        icon="✅",
    )


# ============================================================
# DISPLAY CURRENT / PREVIOUS RUN
# ============================================================


last_run = (
    st.session_state.get(
        "exercise_3_last_run"
    )
)


if last_run:

    run_directory = Path(
        last_run[
            "run_directory"
        ]
    )

    results_directory = (
        run_directory
        / "results"
    )

    logs_directory = (
        run_directory
        / "logs"
    )

    fixed_directory = (
        run_directory
        / "fixed"
    )

    adaptive_directory = (
        run_directory
        / "adaptive"
    )

    inputs_directory = (
        run_directory
        / "inputs"
    )

    compliance_df = (
        read_csv_if_exists(
            results_directory
            / "final_compliance_results.csv"
        )
    )

    details_df = (
        normalise_details_dataframe(
            read_csv_if_exists(
                results_directory
                / "compliance_field_details.csv"
            )
        )
    )

    metadata_df = (
        read_csv_if_exists(
            results_directory
            / "original_metadata.csv"
        )
    )

    fixed_quality_df = (
        read_csv_if_exists(
            results_directory
            / "fixed_quality.csv"
        )
    )

    adaptive_decisions_df = (
        read_csv_if_exists(
            results_directory
            / "adaptive_bitrate_decisions.csv"
        )
    )

    adaptive_quality_df = (
        read_csv_if_exists(
            results_directory
            / "adaptive_quality.csv"
        )
    )

    comparison_df = (
        read_csv_if_exists(
            results_directory
            / "fixed_vs_adaptive_comparison.csv"
        )
    )

    # ========================================================
    # COMPLIANCE DISPLAY
    # ========================================================

    with compliance_tab:

        if not compliance_df.empty:

            st.markdown(
                "### Run Summary"
            )

            original_compliant = int(
                (
                    compliance_df[
                        "original_status"
                    ]
                    == "COMPLIANT"
                ).sum()
            )

            original_noncompliant = int(
                (
                    compliance_df[
                        "original_status"
                    ]
                    == "NON-COMPLIANT"
                ).sum()
            )

            converted_compliant = int(
                (
                    compliance_df[
                        "post_conversion_status"
                    ]
                    == "COMPLIANT"
                ).sum()
            )

            processing_errors = int(
                (
                    compliance_df[
                        "original_status"
                    ]
                    == "ERROR"
                ).sum()
                +
                (
                    compliance_df[
                        "post_conversion_status"
                    ]
                    == "PROCESSING ERROR"
                ).sum()
            )

            (
                c1,
                c2,
                c3,
                c4,
            ) = st.columns(
                4
            )

            c1.metric(
                "Original Compliant",
                original_compliant,
            )

            c2.metric(
                "Original Non-Compliant",
                original_noncompliant,
            )

            c3.metric(
                "Converted Compliant",
                converted_compliant,
            )

            c4.metric(
                "Processing Errors",
                processing_errors,
            )

            st.dataframe(
                compliance_df,
                hide_index=True,
                use_container_width=True,
            )

        # ----------------------------------------------------
        # FIELD-BY-FIELD VERIFICATION
        # ----------------------------------------------------

        if not details_df.empty:

            st.markdown(
                "### Field-by-Field Verification"
            )

            st.caption(
                (
                    "Switch between the submitted ORIGINAL "
                    "files and the post-conversion CONVERTED "
                    "outputs. Converted outputs should display "
                    "9 / 9 PASS."
                )
            )

            available_stages = [
                stage

                for stage
                in [
                    "Original",
                    "Converted",
                ]

                if (
                    stage
                    in details_df[
                        "stage"
                    ].astype(
                        str
                    ).unique()
                )
            ]

            if not available_stages:

                available_stages = [
                    "Original"
                ]

            # ------------------------------------------------
            # IMPORTANT UX FIX:
            # Default to Converted after a successful run.
            # ------------------------------------------------

            default_stage_index = (
                available_stages.index(
                    "Converted"
                )
                if (
                    "Converted"
                    in available_stages
                )
                else 0
            )

            selected_stage = (
                st.radio(
                    "Verification stage",
                    available_stages,
                    index=(
                        default_stage_index
                    ),
                    horizontal=True,
                    key="verification_stage",
                )
            )

            stage_details = (
                details_df[
                    details_df[
                        "stage"
                    ].astype(
                        str
                    )
                    == selected_stage
                ]
            )

            detail_files = sorted(
                stage_details[
                    "input_file"
                ]
                .dropna()
                .astype(
                    str
                )
                .unique()
                .tolist()
            )

            if detail_files:

                selected_detail_file = (
                    st.selectbox(
                        (
                            "Converted output"
                            if (
                                selected_stage
                                == "Converted"
                            )
                            else "Original submission"
                        ),
                        detail_files,
                        key=(
                            "detail_file_"
                            + selected_stage
                        ),
                    )
                )

                selected_details = (
                    stage_details[
                        stage_details[
                            "input_file"
                        ].astype(
                            str
                        )
                        == selected_detail_file
                    ]
                )

                show_verification_table(
                    selected_details,
                    selected_stage,
                )

                if (
                    selected_stage
                    == "Converted"
                ):

                    pass_count = int(
                        (
                            selected_details[
                                "status"
                            ]
                            == "PASS"
                        ).sum()
                    )

                    total_count = (
                        len(
                            selected_details
                        )
                    )

                    st.metric(
                        (
                            "Mandatory Fields Passed"
                        ),
                        (
                            f"{pass_count} / "
                            f"{total_count}"
                        ),
                    )

            else:

                st.info(
                    (
                        "No files are available for "
                        f"the {selected_stage} stage."
                    )
                )

    # ========================================================
    # TRANSCODING DISPLAY
    # ========================================================

    with conversion_container:

        st.markdown(
            "### Fixed-Bitrate H.265 Conversion"
        )

        st.caption(
            (
                "Only canonical `_convertedOK.mp4` outputs "
                "are shown here. The `_formatOK.mp4` files "
                "are equivalent aliases generated for "
                "coursework/rubric compatibility."
            )
        )

        converted_files = (
            canonical_converted_files(
                fixed_directory
            )
        )

        if converted_files:

            selected_output = (
                st.selectbox(
                    "Converted video",
                    converted_files,
                    format_func=lambda path:
                        path.name,
                    key="fixed_output_select",
                )
            )

            corresponding_original = (
                find_original_for_converted(
                    selected_output,
                    inputs_directory,
                )
            )

            (
                before_col,
                after_col,
            ) = st.columns(
                2
            )

            # ------------------------------------------------
            # ORIGINAL
            # ------------------------------------------------

            with before_col:

                st.markdown(
                    "#### Original"
                )

                if (
                    corresponding_original
                    is not None
                    and
                    corresponding_original.is_file()
                ):

                    thumbnail = (
                        extract_thumbnail(
                            corresponding_original
                        )
                    )

                    if thumbnail is not None:

                        st.image(
                            thumbnail,
                            use_container_width=True,
                        )

                    try:

                        original_metrics = (
                            extract_media_metrics(
                                corresponding_original,
                                TOOLS,
                            )
                        )

                        st.write(
                            (
                                f"**Resolution:** "
                                f"{original_metrics['width']}"
                                " × "
                                f"{original_metrics['height']}"
                            )
                        )

                        st.write(
                            (
                                "**Video codec:** "
                                f"{original_metrics['video_codec']}"
                            )
                        )

                        original_fps = (
                            original_metrics.get(
                                "fps"
                            )
                        )

                        st.write(
                            (
                                "**Frame rate:** "
                                +
                                (
                                    f"{original_fps:.3f} fps"
                                    if original_fps
                                    is not None
                                    else "—"
                                )
                            )
                        )

                        st.write(
                            (
                                "**Video bitrate:** "
                                f"{original_metrics.get('video_bitrate_kbps', 0)}"
                                " kb/s"
                            )
                        )

                    except Exception as error:

                        st.warning(
                            (
                                "Unable to display "
                                "source metadata: "
                                f"{error}"
                            )
                        )

                else:

                    st.info(
                        (
                            "Original source could not "
                            "be matched."
                        )
                    )

            # ------------------------------------------------
            # CONVERTED
            # ------------------------------------------------

            with after_col:

                st.markdown(
                    "#### Converted"
                )

                thumbnail = (
                    extract_thumbnail(
                        selected_output
                    )
                )

                if thumbnail is not None:

                    st.image(
                        thumbnail,
                        use_container_width=True,
                    )

                try:

                    converted_metrics = (
                        extract_media_metrics(
                            selected_output,
                            TOOLS,
                        )
                    )

                    st.write(
                        (
                            "**Resolution:** "
                            f"{converted_metrics['width']}"
                            " × "
                            f"{converted_metrics['height']}"
                        )
                    )

                    st.write(
                        (
                            "**Video codec:** "
                            f"{converted_metrics['video_codec']}"
                        )
                    )

                    converted_fps = (
                        converted_metrics.get(
                            "fps"
                        )
                    )

                    st.write(
                        (
                            "**Frame rate:** "
                            +
                            (
                                f"{converted_fps:.3f} fps"
                                if converted_fps
                                is not None
                                else "—"
                            )
                        )
                    )

                    st.write(
                        (
                            "**Video bitrate:** "
                            f"{converted_metrics.get('video_bitrate_kbps', 0)}"
                            " kb/s"
                        )
                    )

                except Exception as error:

                    st.warning(
                        (
                            "Unable to display "
                            "converted metadata: "
                            f"{error}"
                        )
                    )

            # ------------------------------------------------
            # LIVE FFPROBE RE-VERIFICATION
            # ------------------------------------------------

            st.markdown(
                "### Converted File Mandatory Verification"
            )

            try:

                converted_info = (
                    get_video_info(
                        selected_output,
                        TOOLS,
                    )
                )

                converted_rows = (
                    pd.DataFrame(
                        compliance_field_rows(
                            selected_output.name,
                            converted_info,
                            SPEC,
                            stage="Converted",
                        )
                    )
                )

                show_verification_table(
                    converted_rows,
                    "Converted",
                )

            except Exception as error:

                st.exception(
                    error
                )

            # ------------------------------------------------
            # DOWNLOADS
            # ------------------------------------------------

            st.markdown(
                "### Converted Output Downloads"
            )

            safe_download(
                (
                    "⬇ Download "
                    f"{selected_output.name}"
                ),
                selected_output,
                "fixed_output_download",
                mime="video/mp4",
            )

            original_stem = (
                selected_output
                .stem
            )

            if original_stem.endswith(
                "_convertedOK"
            ):

                original_stem = (
                    original_stem[
                        :-len(
                            "_convertedOK"
                        )
                    ]
                )

            format_ok_alias = (
                fixed_directory
                /
                (
                    f"{original_stem}"
                    "_formatOK.mp4"
                )
            )

            if format_ok_alias.is_file():

                safe_download(
                    (
                        "⬇ Download "
                        f"{format_ok_alias.name}"
                    ),
                    format_ok_alias,
                    "format_ok_alias_download",
                    mime="video/mp4",
                )

        else:

            st.info(
                (
                    "No fixed conversion outputs exist "
                    "for this run. This is expected when "
                    "all originals are already compliant "
                    "or when Compliance Check Only was used."
                )
            )

    # ========================================================
    # EXTENSION DISPLAY
    # ========================================================

    with extension_container:

        st.markdown(
            "### Extension 3B · Adaptive Bitrate"
        )

        if not adaptive_decisions_df.empty:

            st.dataframe(
                adaptive_decisions_df,
                hide_index=True,
                use_container_width=True,
            )

            if (
                "input_file"
                in adaptive_decisions_df.columns
                and
                "selected_bitrate_kbps"
                in adaptive_decisions_df.columns
            ):

                chart_data = (
                    adaptive_decisions_df[
                        [
                            "input_file",
                            "selected_bitrate_kbps",
                        ]
                    ]
                    .set_index(
                        "input_file"
                    )
                )

                st.bar_chart(
                    chart_data,
                    use_container_width=True,
                )

        else:

            st.info(
                (
                    "Adaptive bitrate extension "
                    "was not executed."
                )
            )

        st.markdown(
            "### Extension 3A · Quality Evaluation"
        )

        if not fixed_quality_df.empty:

            st.markdown(
                "#### Fixed 3000 kb/s"
            )

            st.dataframe(
                fixed_quality_df,
                hide_index=True,
                use_container_width=True,
            )

        if not adaptive_quality_df.empty:

            st.markdown(
                "#### Adaptive"
            )

            st.dataframe(
                adaptive_quality_df,
                hide_index=True,
                use_container_width=True,
            )

        if (
            fixed_quality_df.empty
            and
            adaptive_quality_df.empty
        ):

            st.info(
                (
                    "PSNR / SSIM quality analysis "
                    "was not executed."
                )
            )

        if not comparison_df.empty:

            st.markdown(
                "### Fixed vs Adaptive"
            )

            st.dataframe(
                comparison_df,
                hide_index=True,
                use_container_width=True,
            )

            if (
                "fixed_mean_psnr_db"
                in comparison_df.columns
                and
                "adaptive_mean_psnr_db"
                in comparison_df.columns
            ):

                psnr = (
                    comparison_df[
                        [
                            "input_file",
                            "fixed_mean_psnr_db",
                            "adaptive_mean_psnr_db",
                        ]
                    ]
                    .set_index(
                        "input_file"
                    )
                )

                st.markdown(
                    "#### PSNR Comparison"
                )

                st.bar_chart(
                    psnr,
                    use_container_width=True,
                )

            if (
                "fixed_mean_ssim"
                in comparison_df.columns
                and
                "adaptive_mean_ssim"
                in comparison_df.columns
            ):

                ssim = (
                    comparison_df[
                        [
                            "input_file",
                            "fixed_mean_ssim",
                            "adaptive_mean_ssim",
                        ]
                    ]
                    .set_index(
                        "input_file"
                    )
                )

                st.markdown(
                    "#### SSIM Comparison"
                )

                st.bar_chart(
                    ssim,
                    use_container_width=True,
                )

    # ========================================================
    # REPORT DOWNLOADS
    # ========================================================

    with report_container:

        st.markdown(
            "### Generated Evidence"
        )

        format_report_path = (
            logs_directory
            / "format_report.txt"
        )

        if format_report_path.is_file():

            st.markdown(
                "#### Format Compliance Report"
            )

            st.code(
                format_report_path
                .read_text(
                    encoding="utf-8"
                )
            )

            safe_download(
                "⬇ format_report.txt",
                format_report_path,
                "download_format_report",
                mime="text/plain",
            )

        extension_report_path = (
            logs_directory
            / "exercise3_extension_report.txt"
        )

        if extension_report_path.is_file():

            st.markdown(
                "#### Extension Report"
            )

            with st.expander(
                "View extension report"
            ):

                st.code(
                    extension_report_path
                    .read_text(
                        encoding="utf-8"
                    )
                )

            safe_download(
                (
                    "⬇ "
                    "exercise3_extension_report.txt"
                ),
                extension_report_path,
                "download_extension_report",
                mime="text/plain",
            )

        st.markdown(
            "### CSV Results"
        )

        csv_files = sorted(
            results_directory.glob(
                "*.csv"
            )
        )

        for index, csv_path in enumerate(
            csv_files
        ):

            safe_download(
                (
                    "⬇ "
                    + csv_path.name
                ),
                csv_path,
                (
                    "csv_"
                    f"{index}"
                ),
                mime="text/csv",
            )

        archive_path = Path(
            last_run[
                "archive_path"
            ]
        )

        if archive_path.is_file():

            st.markdown(
                "### Complete Run Archive"
            )

            safe_download(
                (
                    "⬇ Download complete "
                    "Exercise 3 ZIP"
                ),
                archive_path,
                "download_complete_zip",
                mime="application/zip",
            )

        st.caption(
            "Run directory"
        )

        st.code(
            str(
                run_directory.resolve()
            )
        )


# ============================================================
# EMPTY STATE
# ============================================================


else:

    with conversion_container:

        st.markdown(
            """
            <div class="empty-monitor">

                <div class="monitor-icon">
                    H.265
                </div>

                <div class="monitor-title">
                    Transcoder ready
                </div>

                <div class="monitor-text">
                    Select video files and press
                    <strong>Run Format Analysis</strong>.
                </div>

            </div>
            """,
            unsafe_allow_html=True,
        )

    with extension_container:

        st.info(
            (
                "Enable Extension 3A / 3B "
                "from the sidebar to compare fixed "
                "and adaptive H.265 conversion."
            )
        )

    with report_container:

        st.info(
            (
                "Reports and downloadable evidence "
                "will appear after processing."
            )
        )
